image: christhomas/pipeline-deployer:latest

services:
  - docker:dind

before_script:
  - docker info

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  NAMESPACE: mail-server
  NAME: postfix
  REPLICAS: 1

stages:
  - build
  - deploy

.login_docker: &login_docker
  echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}

build:
  stage: build
  script:
    - *login_docker
    - docker build --pull -t ${CI_REGISTRY_IMAGE}/${NAME}:${CI_PIPELINE_ID} $PWD
    - docker push ${CI_REGISTRY_IMAGE}/${NAME}:${CI_PIPELINE_ID}
    - docker tag ${CI_REGISTRY_IMAGE}/${NAME}:${CI_PIPELINE_ID} ${CI_REGISTRY_IMAGE}/${NAME}:latest
    - docker push ${CI_REGISTRY_IMAGE}/${NAME}:latest

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - echo ${CI_KUBECONFIG} | base64 -d > $PWD/kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl get pods --all-namespaces
    - kubectl scale --replicas=0 deployment/${NAME} || true
    - kubectl get deployments
    - helm template
      -f $PWD/values.yaml
      --set name=${NAME}
      --set namespace=${NAMESPACE}
      --set server.hostname=$(kubectl get configmap connection-map -o=jsonpath="{.data.HOSTNAME}")
      --set port.haproxy_smtpd=$(kubectl get configmap connection-map -o=jsonpath="{.data.POSTFIX_PORT}")
      --set port.plain_smtpd=$(kubectl get configmap connection-map -o=jsonpath="{.data.POSTFIX_SUBMISSION_PORT}")
      --set repository=${CI_REGISTRY_IMAGE}/${NAME}:${CI_PIPELINE_ID}
      --set registry=${CI_REGISTRY}
      --set username=${CI_DEPLOY_USERNAME}
      --set password=${CI_DEPLOY_PASSWORD}
      $PWD/kubernetes | kubectl apply -f -
    - kubectl scale --replicas=${REPLICAS} deployment/${NAME}
    - kubectl get deployments
