apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  ENTRYPOINT_DEBUG: ""
  MESSAGE_SIZE_LIMIT: "{{ .Values.server.message_size_limit }}"
  RELAY_NETS: "{{ .Values.server.relay_nets }}"
  RELAY_HOST: "{{ .Values.server.relay_host }}"
  LOGGING_LEVEL: "{{ .Values.logging_level }}"
