apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}
        role: {{ .Values.name }}
    spec:
      nodeSelector:
        mailserver: "true"
      imagePullSecrets:
        - name: {{ .Values.name }}
      initContainers:
        - name: disable-tcp-window-scaling
          image: busybox
          command: ["sysctl", "-w", "net.ipv4.tcp_window_scaling=0"]
          securityContext:
            privileged: true
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.repository }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
            - configMapRef:
                name: general
            - configMapRef:
                name: services-info
            - configMapRef:
                name: database-read
            - configMapRef:
                name: database-common
          ports:
            - name: haproxy-smtpd
              containerPort: {{ .Values.haproxy_smtpd }}
              protocol: TCP
            - name: plain-smtpd
              containerPort: {{ .Values.plain_smtpd }}
              protocol: TCP
          volumeMounts:
            - name: certificate
              mountPath: /etc/certs/
      volumes:
        - name: certificate
          secret:
            secretName: tls-postfix

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
    role: {{ .Values.name }}
  ports:
    - name: haproxy-smtpd
      port: {{ .Values.haproxy_smtpd }}
      targetPort: {{ .Values.haproxy_smtpd }}
    - name: plain-smtpd
      port: {{ .Values.plain_smtpd }}
      targetPort: {{ .Values.plain_smtpd }}
